#!/usr/bin/env node
/**
 * List every policy BrowseKit enforces, straight from the source of truth
 * (manifest.json + scripts/validate.mjs), so the list can't drift.
 *
 *   npm run policies            # print to the terminal
 *   npm run policies -- --write # also refresh the generated section of docs/POLICIES.md
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALLOWED_OPTIONAL_HOSTS, ALLOWED_PERMISSIONS, BANNED_CODE, URL_ALLOWLIST, validateExtension } from './validate.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));

/** Why each permission exists (keep in sync with architecture.md §4 and PRIVACY.md). */
const WHY = {
  storage: 'Settings and small per-site data in chrome.storage.local (never storage.sync).',
  tabs: 'URLs/titles of tabs you save, search, snooze or de-duplicate. Chrome shows "Read your browsing history".',
  favicon: "Site icons from Chrome's local cache instead of downloading them.",
  contextMenus: 'Right-click "Save to Watch Later" / "Save tab to TabVault".',
  activeTab: 'Temporary access to the current tab after a click or shortcut.',
  scripting: 'Inject media controls / read page text on demand (with activeTab or granted sites).',
  sessions: 'Recently closed tabs and windows.',
  alarms: 'One-minute tick: snooze wake-ups, idle-tab handling, session autosave.',
  sidePanel: 'Optional side-panel view of the popup tools.',
};

const csp = manifest.content_security_policy?.extension_pages ?? '';
const errors = validateExtension(ROOT);
const lines = [];
const out = (s = '') => lines.push(s);

out('<!-- generated by `npm run policies -- --write`; do not edit by hand -->');
out(`### Status (v${manifest.version})`);
out();
out(errors.length ? `**✗ ${errors.length} policy violation(s):**` : '**✓ All policy checks pass** (`npm run validate`).');
for (const e of errors) out(`- ${e}`);
out();
out('### Permissions requested at install');
out();
out('| Permission | Why |');
out('| --- | --- |');
for (const p of manifest.permissions ?? []) out(`| \`${p}\` | ${WHY[p] ?? '**Undocumented — add a reason**'} |`);
out();
out('### Optional host access (asked per site at runtime)');
out();
for (const h of manifest.optional_host_permissions ?? []) out(`- \`${h}\` — only the single site you approve, for automatic Media Boost`);
out(`- Install-time host permissions: ${(manifest.host_permissions ?? []).length ? manifest.host_permissions.join(', ') : '**none**'}`);
out();
out('### Permission allow-list (anything else fails validation)');
out();
out([...ALLOWED_PERMISSIONS].map((p) => `\`${p}\``).join(', '));
out(`Optional hosts allowed: ${[...ALLOWED_OPTIONAL_HOSTS].map((p) => `\`${p}\``).join(', ')}`);
out();
out('### Content Security Policy (extension pages + service worker)');
out();
for (const d of csp.split(';').map((x) => x.trim()).filter(Boolean)) out(`- \`${d}\``);
out();
out('### Banned in shipped source (`src/`)');
out();
for (const [re, what] of BANNED_CODE) out(`- ${what} — \`${re.source}\``);
out('- Literal remote `http(s)://` URLs, except: ' + URL_ALLOWLIST.map((r) => `\`${r.source}\``).join(', '));
out('- Bare/remote `import` specifiers (no dependencies) and missing imports');
out('- Inline `<script>`, `<style>`, `style=""` and `on*=""` handlers in HTML');
out('- ES `import`/`export` in content scripts (they must be classic scripts)');
out();
out('### Keyboard commands');
out();
for (const [name, c] of Object.entries(manifest.commands ?? {})) {
  out(`- \`${name}\` — ${c.description ?? 'Open the popup'}${c.suggested_key?.default ? ` (default ${c.suggested_key.default})` : ''}`);
}

const text = lines.join('\n');
console.log(text);

if (process.argv.includes('--write')) {
  const docPath = join(ROOT, 'docs', 'POLICIES.md');
  const doc = readFileSync(docPath, 'utf8');
  const start = '<!-- POLICIES:START -->';
  const end = '<!-- POLICIES:END -->';
  const next = doc.replace(new RegExp(`${start}[\\s\\S]*?${end}`), `${start}\n${text}\n${end}`);
  writeFileSync(docPath, next);
  console.error(`\nUpdated ${docPath}`);
}
process.exitCode = errors.length ? 1 : 0;
